import LogoCardano from "@/assets/logo-cardano.png";

export const list_tokens_eth = [
  {
    ticker: "eth",
    name: "ETH (ERC20)",
    image: "/uploads/eth_f4ebb54ec0.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "eth",
  },
  {
    ticker: "usdt",
    name: "USDT (ERC20)",
    image: "/uploads/usdterc20_5ae21618aa.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: true,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    buy: true,
    sell: true,
    legacyTicker: "usdterc20",
  },
  {
    ticker: "dai",
    name: "Dai (ERC20)",
    image: "/uploads/dai_5315155551.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: "0x6b175474e89094c44da98b954eedeac495271d0f",
    buy: true,
    sell: true,
    legacyTicker: "dai",
  },
  {
    ticker: "aave",
    name: "Aave (ERC20)",
    image: "/uploads/aave_10a92c0ead.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
    buy: true,
    sell: true,
    legacyTicker: "aave",
  },
  {
    ticker: "woo",
    name: "WOO Network (ERC20)",
    image: "/uploads/wooeth_3ce3789236.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "eth",
    tokenContract: "0x4691937a7508860F876c9c0a2a617E7d9E945D4B",
    buy: true,
    sell: true,
    legacyTicker: "woo",
  },
];

export const list_tokens_arb = [
  {
    ticker: "arb",
    name: "Arbitrum (ARB20)",
    image: "/uploads/arb_b711c7cb0b.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "arbitrum",
    tokenContract: "0x912CE59144191C1204E64559FE8253a0e49E6548",
    buy: true,
    sell: true,
    legacyTicker: "arb",
  },
  {
    ticker: "eth",
    name: "Ethereum (ARB20)",
    image: "/uploads/etharbitrum_796401be67.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "arbitrum",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "etharb",
  },
  {
    ticker: "usdt",
    name: "USDT (ARB20)",
    image: "/uploads/usdtarb_86018e11fd.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "arbitrum",
    tokenContract: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9",
    buy: true,
    sell: true,
    legacyTicker: "usdtarb",
  },
  {
    ticker: "dai",
    name: "Dai (ARB20)",
    image: "/uploads/daiarb_99c098d102.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "arbitrum",
    tokenContract: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
    buy: true,
    sell: true,
    legacyTicker: "daiarb",
  },
  {
    ticker: "woo",
    name: "WOO Network (ARB20)",
    image: "/uploads/wooarb_99dd880928.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "arbitrum",
    tokenContract: "0xcAFcD85D8ca7Ad1e1C6F82F651fA15E33AEfD07b",
    buy: true,
    sell: true,
    legacyTicker: "wooarb",
  },
];

export const list_tokens_bsc = [
  {
    ticker: "bnb",
    name: "BNB (BEP20)",
    image: "/uploads/bnbbsc_331e969a6b.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "bsc",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "bnbbsc",
  },
  {
    ticker: "usdt",
    name: "USDT (BEP20)",
    image: "/uploads/usdtbsc_b8f3d8f316.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "bsc",
    tokenContract: "0x55d398326f99059fF775485246999027B3197955",
    buy: true,
    sell: true,
    legacyTicker: "usdtbsc",
  },
  {
    ticker: "dai",
    name: "Dai (BEP20)",
    image: "/uploads/daibsc_9cc7dd8c68.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "bsc",
    tokenContract: "",
    buy: true,
    sell: true,
    legacyTicker: "daibsc",
  },
  {
    ticker: "woo",
    name: "WOO Network (BEP20)",
    image: "/uploads/woobsc_a2e0b40f2a.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "bsc",
    tokenContract: "0x4691937a7508860F876c9c0a2a617E7d9E945D4B",
    buy: true,
    sell: true,
    legacyTicker: "woobsc",
  },
];

export const list_tokens_sol = [
  {
    ticker: "sol",
    name: "Solana (SOL)",
    image: "/uploads/sol_3b3f795997.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "sol",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "sol",
  },
  {
    ticker: "usdt",
    name: "USDT (SOL)",
    image: "/uploads/usdtsol_4f6a1c5208.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "sol",
    tokenContract: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    buy: true,
    sell: true,
    legacyTicker: "usdtsol",
  },
  // {
  //   ticker: "usdc",
  //   name: "USDC (SOL)",
  //   image: "/uploads/usdcsol_9415198300.svg",
  //   hasExternalId: false,
  //   isFiat: false,
  //   featured: false,
  //   isStable: true,
  //   supportsFixedRate: true,
  //   network: "sol",
  //   tokenContract: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  //   buy: true,
  //   sell: true,
  //   legacyTicker: "usdcsol",
  // },
  {
    ticker: "hnt",
    name: "Helium (SOL)",
    image: "/uploads/HNT_ecdd4e088e.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "sol",
    tokenContract: "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux",
    buy: true,
    sell: true,
    legacyTicker: "hntsol",
  },
  {
    ticker: "bonk",
    name: "Bonk (SOL)",
    image: "/uploads/bonk_35ec61fbab.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "sol",
    tokenContract: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    buy: true,
    sell: true,
    legacyTicker: "bonk",
  },
  {
    ticker: "pyth",
    name: "Pyth Network (SOL)",
    image: "/uploads/pyth_7e8ece761a.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "sol",
    tokenContract: "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    buy: true,
    sell: true,
    legacyTicker: "pyth",
  },
];

export const list_tokens_trx = [
  {
    ticker: "trx",
    name: "TRON (TRC20)",
    image: "/uploads/trx_f14430166e.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "trx",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "trx",
  },
  {
    ticker: "usdt",
    name: "USDT (TRC20)",
    image: "/uploads/usdttrc20_87164a7b35.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "trx",
    tokenContract: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    buy: true,
    sell: true,
    legacyTicker: "usdttrc20",
  },
  // {
  //   ticker: "usdc",
  //   name: "USDC (TRC20)",
  //   image: "/uploads/usdctrc20_d13d6907e1.svg",
  //   hasExternalId: false,
  //   isFiat: false,
  //   featured: false,
  //   isStable: true,
  //   supportsFixedRate: true,
  //   network: "trx",
  //   tokenContract: "TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8",
  //   buy: true,
  //   sell: true,
  //   legacyTicker: "usdctrc20",
  // },
  {
    ticker: "klv",
    name: "Klever (TRC20)",
    image: "/uploads/klv_f9ec0ffcfb.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "trx",
    tokenContract: "TVj7RNVHy6thbM7BWdSe9G6gXwKhjhdNZS",
    buy: true,
    sell: true,
    legacyTicker: "klv",
  },
  // {
  //   ticker: "sun",
  //   name: "Sun (TRC20)",
  //   image: "/uploads/sun_cb41379057.svg",
  //   hasExternalId: false,
  //   isFiat: false,
  //   featured: false,
  //   isStable: false,
  //   supportsFixedRate: true,
  //   network: "trx",
  //   tokenContract: "TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S",
  //   buy: true,
  //   sell: true,
  //   legacyTicker: "sun",
  // },
];

export const list_tokens_op = [
  {
    ticker: "op",
    name: "Optimism",
    image: "/uploads/op_e3944c4cf9.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "op",
    tokenContract: "0x4200000000000000000000000000000000000042",
    buy: true,
    sell: true,
    legacyTicker: "op",
  },
  {
    ticker: "usdt",
    name: "USDT (Optimism)",
    image: "/uploads/usdtop_32489c0777.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
    network: "op",
    tokenContract: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58",
    buy: true,
    sell: true,
    legacyTicker: "usdtop",
  },
  {
    ticker: "wld",
    name: "Worldcoin (Optimism)",
    image: "/uploads/wldop_706614f87e.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "op",
    tokenContract: "0xdC6fF44d5d932Cbd77B52E5612Ba0529DC6226F1",
    buy: true,
    sell: true,
    legacyTicker: "wldop",
  },
  {
    ticker: "cyber",
    name: "CyberConnect (Optimism)",
    image: "/uploads/cyberop_f0350b635c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "op",
    tokenContract: "0x14778860E937f509e651192a90589dE711Fb88a9",
    buy: true,
    sell: true,
    legacyTicker: "cyberop",
  },
];

export const list_tokens = [
  ...list_tokens_eth,
  ...list_tokens_bsc,
  ...list_tokens_arb,
  ...list_tokens_sol,
  ...list_tokens_trx,
  ...list_tokens_op,
  {
    ticker: "btc",
    name: "Bitcoin (BTC)",
    image: "/uploads/btc_1_527dc9ec3c.svg",
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "btc",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "btc",
  },
  {
    ticker: "xrp",
    name: "Ripple (XRP)",
    image: "/uploads/xrp_3b5212fd4a.svg",
    hasExternalId: true,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "xrp",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "xrp",
  },
  {
    ticker: "ftm",
    name: "Fantom (FTM)",
    image: "/uploads/ftm_801088098f.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "ftm",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "ftmmainnet",
  },
  {
    ticker: "avax",
    name: "Avalanche",
    image: "/uploads/avaxs_4e906c3ad4.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "cchain",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "avaxc",
  },
  {
    ticker: "eth",
    name: "Ethereum (Base)",
    image: "/uploads/ethbase_42ce14857a.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "base",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "ethbase",
  },
  {
    ticker: "matic",
    name: "Polygon",
    image: "/uploads/matic_token_f9906e3f5d.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "matic",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "maticmainnet",
  },
  {
    ticker: "tia",
    name: "Celestia",
    image: "/uploads/tia_4ed44a458a.svg",
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "tia",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "tia",
  },
  {
    ticker: "sei",
    name: "Sei",
    image: "/uploads/sei_fda6fbd2c1.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "sei",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "seimainnet",
  },
  {
    ticker: "ada",
    name: "Cardano (ADA)",
    image: LogoCardano.src,
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
    network: "ada",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "ada",
  },
  {
    ticker: "inj",
    name: "Injective",
    image: "/uploads/injmainnet_c155cd4e32.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
    network: "inj",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "injmainnet",
  },
];

export const list_tokens_extra = [
  {
    ticker: "sui",
    name: "Sui (Beta)",
    image: "/uploads/sui_6d4e2efb11.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
    network: "sui",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "suimainnet",
  },
  {
    ticker: "rose",
    name: "Oasis Network (Beta)",
    image: "/uploads/rosemainnet_e09f8a3d6a.svg",
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
    network: "rose",
    tokenContract: null,
    buy: true,
    sell: true,
    legacyTicker: "rosemainnet",
  },
];
